language: php

cache:
  directories:
    - $HOME/.composer/cache
    -
php:
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: 7.3
    - php: nightly
  
install:
   - composer install

script:
  - composer test