apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app.kubernetes.io/part-of: tum-cal-proxy
    app.kubernetes.io/name: server
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: tum-cal-proxy
      app.kubernetes.io/name: server
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: tum-cal-proxy
        app.kubernetes.io/name: server
    spec:
      containers:
        - name: sexy-server
          image: ghcr.io/tum-dev/calendarproxy/server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: https
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
