apiVersion: v1
kind: Service
metadata:
  name: tum-cal-proxy-svc
  labels:
    app.kubernetes.io/part-of: tum-cal-proxy
    app.kubernetes.io/name: server
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: tum-cal-proxy
    app.kubernetes.io/name: server
  ports:
    - name: server
      port: 80
      targetPort: 80